### ISSUE TITLE
Publish dry run fails: OrthoConfigSubcommandDocs missing from published ortho_config_macros 0.8.0

### ISSUE THREAD

**Issue by leynos** [leynos/ortho-config#414]
## Context

CI workflow run 30870855850 fails the `Publish dry run` step on both
matrix legs (the failure predates the Whitaker unpin in e64b55f; earlier
runs failed too). The `Lint` step passes.

## Failure

`lading publish` (dry run) fails while verifying the `ortho_config`
0.8.0 package tarball:

```text
error[E0432]: unresolved import `ortho_config_macros::OrthoConfigSubcommandDocs`
  --> src/lib.rs:12:44
   |
12 | pub use ortho_config_macros::{OrthoConfig, OrthoConfigSubcommandDocs};
   |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^ no `OrthoConfigSubcommandDocs` in the root
```

The workspace `ortho_config_macros` exports `OrthoConfigSubcommandDocs`,
but the crates.io release of `ortho_config_macros` 0.8.0 does not. Both
carry the same version number, so tarball verification resolves the
dependency to the published 0.8.0 and the re-export in
`ortho_config/src/lib.rs:12` fails to compile.

The windows leg additionally hits a `UnicodeEncodeError` ('ś',
cp1252) in the log-relay wrapper while streaming the same failure.

## Remediation

The workspace has drifted from the published macros crate without a
version bump. Bump the affected crate versions so the unpublished macros
change is versioned ahead of crates.io, keeping the publish dry run's
unpublished-workspace-dependency allowance effective, or otherwise
release `ortho_config_macros` with the new export before the next
`ortho_config` release.
